vsim work.if_id_tb

add wave  \
sim:/if_id_tb/opcode \
sim:/if_id_tb/ALUsrc \
sim:/if_id_tb/ALUop \
sim:/if_id_tb/RegDst \
sim:/if_id_tb/clk \
sim:/if_id_tb/reset \
sim:/if_id_tb/PCin \
sim:/if_id_tb/PCout \
sim:/if_id_tb/pcSrc \
sim:/if_id_tb/addressMem \
sim:/if_id_tb/instructionMem \
sim:/if_id_tb/IF_PC \
sim:/if_id_tb/IF_Instruction \
sim:/if_id_tb/ID_PC \
sim:/if_id_tb/ID_Instruction \
sim:/if_id_tb/addOne \
sim:/if_id_tb/zeros \
sim:/if_id_tb/RegWrite \
sim:/if_id_tb/write_data \
sim:/if_id_tb/read_address1 \
sim:/if_id_tb/read_address2 \
sim:/if_id_tb/write_address \
sim:/if_id_tb/read_data1 \
sim:/if_id_tb/read_data2 \
sim:/if_id_tb/CU_MemToReg \
sim:/if_id_tb/CU_MemRead \
sim:/if_id_tb/CU_MemWrite \
sim:/if_id_tb/Branch \
sim:/if_id_tb/ID_ReadData1 \
sim:/if_id_tb/ID_ReadData2 \
sim:/if_id_tb/ID_SignExtImm \
sim:/if_id_tb/ID_RegAddr1 \
sim:/if_id_tb/ID_RegAddr2 \
sim:/if_id_tb/ID_PCSrc \
sim:/if_id_tb/ID_RegDst \
sim:/if_id_tb/ID_ALUsrc \
sim:/if_id_tb/ID_MemToReg \
sim:/if_id_tb/ID_RegWrite \
sim:/if_id_tb/ID_MemRead \
sim:/if_id_tb/ID_MemWrite \
sim:/if_id_tb/ID_Branch \
sim:/if_id_tb/ID_ALUop \
sim:/if_id_tb/EX_zero \
sim:/if_id_tb/EX_PC \
sim:/if_id_tb/EX_Instruction \
sim:/if_id_tb/EX_ReadData1 \
sim:/if_id_tb/EX_ReadData2 \
sim:/if_id_tb/EX_SignExtImm \
sim:/if_id_tb/EX_RegAddr1 \
sim:/if_id_tb/EX_RegAddr2 \
sim:/if_id_tb/EX_PCSrc \
sim:/if_id_tb/EX_RegDst \
sim:/if_id_tb/EX_ALUsrc \
sim:/if_id_tb/EX_MemToReg \
sim:/if_id_tb/EX_RegWrite \
sim:/if_id_tb/EX_MemRead \
sim:/if_id_tb/EX_MemWrite \
sim:/if_id_tb/EX_Branch \
sim:/if_id_tb/EX_ALUop \
sim:/if_id_tb/opA \
sim:/if_id_tb/opB \
sim:/if_id_tb/funct \
sim:/if_id_tb/ALUout \
sim:/if_id_tb/carryOut \
sim:/if_id_tb/zero \
sim:/if_id_tb/EX_ALUresult \
sim:/if_id_tb/EX_DestReg \
sim:/if_id_tb/MEM_zero \
sim:/if_id_tb/MEM_ALUresult \
sim:/if_id_tb/MEM_ReadData2 \
sim:/if_id_tb/MEM_MemRead \
sim:/if_id_tb/MEM_MemWrite \
sim:/if_id_tb/MEM_MemToReg \
sim:/if_id_tb/MEM_Branch \
sim:/if_id_tb/MEM_DestReg \
sim:/if_id_tb/addr \
sim:/if_id_tb/data_in \
sim:/if_id_tb/data_out \
sim:/if_id_tb/MEM_MemDataOut \
sim:/if_id_tb/WB_MemToReg \
sim:/if_id_tb/WB_MemDataOut \
sim:/if_id_tb/WB_ALUresult \
sim:/if_id_tb/uut_CU/currentState


run 300 ns